### ISSUE TITLE
Google drive permission.

### ISSUE THREAD

**Issue by moovs** [cross-solutions/smart-notes#15]
Hi, why I need to give access for my Google Drive? What reason? This is necessary to order to synchronize notes in my Google Drive?

**Comment by dustincatap** [comment]
Hi. Yes this will be used for storing application-specific data. The data, which ia a JSON file, will not be visible to the user's Google Drive folder, it can only be accessed by the app itself. 

More info [here](https://developers.google.com/drive/api/v3/appdata).
